### ISSUE TITLE
Configuration with newer Node version

### ISSUE THREAD

**Issue by Bakerbakura** [minhd-vu/assassins#43]
Hello there

Disclaimer: This is my first time using `node`, `npm`, etc.

I tried following the given installation instructions, but unfortunately it seems the version of `node` I have on my laptop is too new. I got the following error:
```
$ npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: assassins@0.1.0
npm ERR! notsup Not compatible with your version of node/npm: assassins@0.1.0
npm ERR! notsup Required: {"node":"15.x","npm":">=7.0.0"}
npm ERR! notsup Actual:   {"npm":"9.6.0","node":"v18.7.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liam/.npm/_logs/2023-03-02T09_35_33_211Z-debug-0.log
```

I'm on Ubuntu 22.10, and it seems that the default version of `node` here, `18.7.0`, is too new.

1. I tried changing `package.json` to force running on my newer version of `node` and installed successfully, but then running the app failed. How do I force the app to run on a specific version of `node`?
2. Could the code base be upgraded to work for newer versions of `node`?

**Comment by minhd-vu** [comment]
Yeah let me try to upgrade it

**Comment by minhd-vu** [comment]
Hey! I had some trouble upgrading the packages so I just remade the entire app using Next.js. It's using node version `20.x` now, so I think you should be able to run it. It's also deployed [here](https://assassinspartygame.vercel.app/) if you want to check it out. It has all the major features, and I'll continue to improve the UI/UX. Let me know if you encounter any issues!
